"""tkinter GUI for the project builder."""

from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext

from builder import ProjectBuilder
from parser import ParseError, parse_dsl


SAMPLE_DSL = """dir: 素材作成/00_rules/
file: 素材作成/00_rules/empty.txt
write: 素材作成/00_rules/readme.md
# 素材作成ルール

Generated by project_builder.
---
"""


class ProjectBuilderApp(tk.Tk):
    """Main GUI window."""

    def __init__(self) -> None:
        super().__init__()
        self.base_dir: Path | None = None
        self.title("Project Builder")
        self.geometry("900x700")
        self.minsize(700, 500)
        self._build_widgets()

    def _build_widgets(self) -> None:
        self.columnconfigure(0, weight=1)
        self.rowconfigure(2, weight=1)
        self.rowconfigure(5, weight=1)

        base_frame = tk.Frame(self)
        base_frame.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 4))
        base_frame.columnconfigure(1, weight=1)

        tk.Button(base_frame, text="Select base folder", command=self._select_base_dir).grid(
            row=0, column=0, sticky="w"
        )
        self.base_dir_var = tk.StringVar(value="No base folder selected")
        tk.Label(base_frame, textvariable=self.base_dir_var, anchor="w").grid(
            row=0, column=1, sticky="ew", padx=(8, 0)
        )

        tk.Label(self, text="DSL input (paths are relative to the base folder, UTF-8)").grid(
            row=1, column=0, sticky="w", padx=10, pady=(6, 4)
        )

        self.dsl_text = scrolledtext.ScrolledText(self, wrap=tk.NONE, height=14)
        self.dsl_text.grid(row=2, column=0, sticky="nsew", padx=10)
        self.dsl_text.insert("1.0", SAMPLE_DSL)

        button_frame = tk.Frame(self)
        button_frame.grid(row=3, column=0, sticky="ew", padx=10, pady=8)

        tk.Button(button_frame, text="Build", command=self._on_build).pack(side=tk.LEFT)
        tk.Button(button_frame, text="Clear log", command=self._clear_log).pack(
            side=tk.LEFT, padx=(8, 0)
        )

        tk.Label(self, text="Creation log").grid(
            row=4, column=0, sticky="sw", padx=10, pady=(4, 4)
        )

        self.log_text = scrolledtext.ScrolledText(
            self, wrap=tk.NONE, height=10, state=tk.DISABLED
        )
        self.log_text.grid(row=5, column=0, sticky="nsew", padx=10, pady=(0, 10))

    def _select_base_dir(self) -> None:
        selected_dir = filedialog.askdirectory(title="Select base folder")
        if not selected_dir:
            return
        self.base_dir = Path(selected_dir)
        self.base_dir_var.set(str(self.base_dir))
        self._append_log(f"BASE dir: {self.base_dir}")

    def _on_build(self) -> None:
        if self.base_dir is None:
            messagebox.showwarning("Project Builder", "Select a base folder first.")
            return

        dsl = self.dsl_text.get("1.0", tk.END)

        try:
            items = parse_dsl(dsl)
            logs = ProjectBuilder(self.base_dir).build(items)
        except (OSError, ParseError) as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        if not logs:
            logs = ["No items to build."]

        self._append_log("\n".join(logs))
        messagebox.showinfo("Project Builder", "Build finished.")

    def _append_log(self, message: str) -> None:
        self.log_text.configure(state=tk.NORMAL)
        if self.log_text.get("1.0", tk.END).strip():
            self.log_text.insert(tk.END, "\n")
        self.log_text.insert(tk.END, message + "\n")
        self.log_text.configure(state=tk.DISABLED)
        self.log_text.see(tk.END)

    def _clear_log(self) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.delete("1.0", tk.END)
        self.log_text.configure(state=tk.DISABLED)
