"""tkinter GUI for the project builder."""

import tkinter as tk
from tkinter import messagebox, scrolledtext

from builder import ProjectBuilder
from parser import ParseError, parse_dsl


SAMPLE_DSL = """dir: C:\\work\\sample_project
file: C:\\work\\sample_project\\empty.txt
write: C:\\work\\sample_project\\README.md
# sample_project

Generated by project_builder.
---
"""


class ProjectBuilderApp(tk.Tk):
    """Main GUI window."""

    def __init__(self) -> None:
        super().__init__()
        self.title("Project Builder")
        self.geometry("900x700")
        self.minsize(700, 500)
        self._build_widgets()

    def _build_widgets(self) -> None:
        self.columnconfigure(0, weight=1)
        self.rowconfigure(1, weight=1)
        self.rowconfigure(4, weight=1)

        tk.Label(self, text="DSL input (absolute paths only, UTF-8)").grid(
            row=0, column=0, sticky="w", padx=10, pady=(10, 4)
        )

        self.dsl_text = scrolledtext.ScrolledText(self, wrap=tk.NONE, height=14)
        self.dsl_text.grid(row=1, column=0, sticky="nsew", padx=10)
        self.dsl_text.insert("1.0", SAMPLE_DSL)

        button_frame = tk.Frame(self)
        button_frame.grid(row=2, column=0, sticky="ew", padx=10, pady=8)

        tk.Button(button_frame, text="Build", command=self._on_build).pack(side=tk.LEFT)
        tk.Button(button_frame, text="Clear log", command=self._clear_log).pack(
            side=tk.LEFT, padx=(8, 0)
        )

        tk.Label(self, text="Creation log").grid(
            row=3, column=0, sticky="sw", padx=10, pady=(4, 4)
        )

        self.log_text = scrolledtext.ScrolledText(self, wrap=tk.NONE, height=10, state=tk.DISABLED)
        self.log_text.grid(row=4, column=0, sticky="nsew", padx=10, pady=(0, 10))

    def _on_build(self) -> None:
        dsl = self.dsl_text.get("1.0", tk.END)

        try:
            items = parse_dsl(dsl)
            logs = ProjectBuilder().build(items)
        except (OSError, ParseError) as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        if not logs:
            logs = ["No items to build."]

        self._append_log("\n".join(logs))
        messagebox.showinfo("Project Builder", "Build finished.")

    def _append_log(self, message: str) -> None:
        self.log_text.configure(state=tk.NORMAL)
        if self.log_text.get("1.0", tk.END).strip():
            self.log_text.insert(tk.END, "\n")
        self.log_text.insert(tk.END, message + "\n")
        self.log_text.configure(state=tk.DISABLED)
        self.log_text.see(tk.END)

    def _clear_log(self) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.delete("1.0", tk.END)
        self.log_text.configure(state=tk.DISABLED)
