"""tkinter GUI for the project builder."""

from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, simpledialog, ttk

from builder import ProjectBuilder
from folder_analyzer import folder_to_dsl
from parser import ParseError, parse_dsl
from presets import PresetError, list_presets, load_preset, make_preset_path, save_preset


SAMPLE_DSL = """dir: 素材作成/00_rules/
file: 素材作成/00_rules/empty.txt
write: 素材作成/00_rules/readme.md
# 素材作成ルール

Generated by project_builder.
---
"""


class ProjectBuilderApp(tk.Tk):
    """Main GUI window."""

    def __init__(self) -> None:
        super().__init__()
        self.base_dir: Path | None = None
        self.preset_paths: dict[str, Path] = {}
        self.title("Project Builder")
        self.geometry("980x760")
        self.minsize(780, 560)
        self._build_widgets()
        self._refresh_presets()

    def _build_widgets(self) -> None:
        self.columnconfigure(0, weight=1)
        self.rowconfigure(3, weight=1)
        self.rowconfigure(6, weight=1)

        base_frame = tk.Frame(self)
        base_frame.grid(row=0, column=0, sticky="ew", padx=10, pady=(10, 4))
        base_frame.columnconfigure(1, weight=1)

        tk.Button(base_frame, text="Select base folder", command=self._select_base_dir).grid(
            row=0, column=0, sticky="w"
        )
        self.base_dir_var = tk.StringVar(value="No base folder selected")
        tk.Label(base_frame, textvariable=self.base_dir_var, anchor="w").grid(
            row=0, column=1, sticky="ew", padx=(8, 0)
        )

        preset_frame = tk.Frame(self)
        preset_frame.grid(row=1, column=0, sticky="ew", padx=10, pady=4)
        preset_frame.columnconfigure(1, weight=1)

        tk.Label(preset_frame, text="Preset").grid(row=0, column=0, sticky="w")
        self.preset_var = tk.StringVar()
        self.preset_combo = ttk.Combobox(
            preset_frame, textvariable=self.preset_var, state="readonly"
        )
        self.preset_combo.grid(row=0, column=1, sticky="ew", padx=(8, 0))
        tk.Button(preset_frame, text="Load", command=self._load_selected_preset).grid(
            row=0, column=2, padx=(8, 0)
        )
        tk.Button(preset_frame, text="Save", command=self._save_preset).grid(
            row=0, column=3, padx=(8, 0)
        )
        tk.Button(preset_frame, text="Refresh", command=self._refresh_presets).grid(
            row=0, column=4, padx=(8, 0)
        )
        tk.Button(preset_frame, text="Analyze folder", command=self._analyze_folder).grid(
            row=0, column=5, padx=(8, 0)
        )

        tk.Label(self, text="DSL input (paths are relative to the base folder, UTF-8)").grid(
            row=2, column=0, sticky="w", padx=10, pady=(6, 4)
        )

        self.dsl_text = scrolledtext.ScrolledText(self, wrap=tk.NONE, height=14)
        self.dsl_text.grid(row=3, column=0, sticky="nsew", padx=10)
        self.dsl_text.insert("1.0", SAMPLE_DSL)

        button_frame = tk.Frame(self)
        button_frame.grid(row=4, column=0, sticky="ew", padx=10, pady=8)

        tk.Button(button_frame, text="Build", command=self._on_build).pack(side=tk.LEFT)
        tk.Button(button_frame, text="Clear log", command=self._clear_log).pack(
            side=tk.LEFT, padx=(8, 0)
        )

        tk.Label(self, text="Creation log").grid(
            row=5, column=0, sticky="sw", padx=10, pady=(4, 4)
        )

        self.log_text = scrolledtext.ScrolledText(
            self, wrap=tk.NONE, height=10, state=tk.DISABLED
        )
        self.log_text.grid(row=6, column=0, sticky="nsew", padx=10, pady=(0, 10))

    def _refresh_presets(self) -> None:
        try:
            preset_paths = list_presets()
        except OSError as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        self.preset_paths = {path.name: path for path in preset_paths}
        names = list(self.preset_paths)
        self.preset_combo.configure(values=names)
        if names and self.preset_var.get() not in names:
            self.preset_var.set(names[0])
        if not names:
            self.preset_var.set("")

    def _load_selected_preset(self) -> None:
        preset_name = self.preset_var.get()
        preset_path = self.preset_paths.get(preset_name)
        if preset_path is None:
            messagebox.showwarning("Project Builder", "Select a preset first.")
            return

        try:
            content = load_preset(preset_path)
        except OSError as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        self._replace_dsl(content)
        self._append_log(f"LOAD preset: {preset_path}")

    def _save_preset(self) -> None:
        preset_name = simpledialog.askstring("Save preset", "Preset file name:", parent=self)
        if preset_name is None:
            return

        try:
            preset_path = make_preset_path(preset_name)
        except PresetError as error:
            messagebox.showerror("Project Builder", str(error))
            return

        if preset_path.exists():
            should_overwrite = messagebox.askyesno(
                "Project Builder", f"{preset_path.name} already exists. Overwrite?"
            )
            if not should_overwrite:
                return

        try:
            save_preset(preset_path, self.dsl_text.get("1.0", tk.END).rstrip() + "\n")
        except OSError as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        self._append_log(f"SAVE preset: {preset_path}")
        self._refresh_presets()
        self.preset_var.set(preset_path.name)

    def _analyze_folder(self) -> None:
        selected_dir = filedialog.askdirectory(title="Select folder to analyze")
        if not selected_dir:
            return

        try:
            dsl = folder_to_dsl(selected_dir)
        except OSError as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        self._replace_dsl(dsl + ("\n" if dsl else ""))
        self._append_log(f"ANALYZE folder: {Path(selected_dir)}")

    def _select_base_dir(self) -> None:
        selected_dir = filedialog.askdirectory(title="Select base folder")
        if not selected_dir:
            return
        self.base_dir = Path(selected_dir)
        self.base_dir_var.set(str(self.base_dir))
        self._append_log(f"BASE dir: {self.base_dir}")

    def _on_build(self) -> None:
        if self.base_dir is None:
            messagebox.showwarning("Project Builder", "Select a base folder first.")
            return

        dsl = self.dsl_text.get("1.0", tk.END)

        try:
            items = parse_dsl(dsl)
            logs = ProjectBuilder(self.base_dir).build(items)
        except (OSError, ParseError) as error:
            messagebox.showerror("Project Builder", str(error))
            self._append_log(f"ERROR: {error}")
            return

        if not logs:
            logs = ["No items to build."]

        self._append_log("\n".join(logs))
        messagebox.showinfo("Project Builder", "Build finished.")

    def _replace_dsl(self, content: str) -> None:
        self.dsl_text.delete("1.0", tk.END)
        self.dsl_text.insert("1.0", content)

    def _append_log(self, message: str) -> None:
        self.log_text.configure(state=tk.NORMAL)
        if self.log_text.get("1.0", tk.END).strip():
            self.log_text.insert(tk.END, "\n")
        self.log_text.insert(tk.END, message + "\n")
        self.log_text.configure(state=tk.DISABLED)
        self.log_text.see(tk.END)

    def _clear_log(self) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.delete("1.0", tk.END)
        self.log_text.configure(state=tk.DISABLED)
